### ISSUE TITLE
Not working with HT 0.7 ?

### ISSUE THREAD

**Issue by vimuel** [nboldi/haskell-tools-atom#28]
![screen shot 2017-05-30 at 20 06 10](https://cloud.githubusercontent.com/assets/17603372/26600303/7f8aa2a2-4573-11e7-8455-a79f3eaa3173.png)

**Comment by nboldi** [comment]
I think the problem shows that the server version is older. Are you sure that it is `0.7`? Please check the executable path in the plugins settings. Is that the latest executable?

**Comment by vimuel** [comment]
Hi. Sorry for late reply. How do I get the version number? I tried `ht-daemon --version`, but that didn't work.

**Comment by nboldi** [comment]
No, we don't have that flag yet. Use cabal or stack to determine the version of the `haskell-tools-daemon` package you installed.

**Comment by vimuel** [comment]
My bad, I had installed 0.5.
