### ISSUE TITLE
Refactoring not working, but error message unclear

### ISSUE THREAD

**Issue by vimuel** [nboldi/haskell-tools-atom#30]
I try renaming the definition of `stuff` and this happens:

<img width="1114" alt="screen shot 2017-06-12 at 19 17 25" src="https://user-images.githubusercontent.com/17603372/27048460-d8b35c40-4fa3-11e7-8e08-f8e0e2470bbc.png">

**Comment by nboldi** [comment]
Before actually refactoring, you need to add your package to the engine. It can be done by right clicking the folder containing the haskell source file and selecting "Add to Haskell-tools". If you are developing a cabal package, you should add the folder containing your `.cabal` file.

**Comment by vimuel** [comment]
Thank you, this worked; but is this documented anywhere?

**Comment by vimuel** [comment]
I need to qualify what I said: I **did** find an option "Add to Haskell-tools". I still can't refactor anything though. It just says "Refactoring", but nothing happens. I wasn't sure whether to open a new issue.

**Comment by nboldi** [comment]
Interesting. Did you start the server before refactoring (Haskell/Start Server)? Did it show the messages in the status bar "Calculating" and "Ready"?

**Comment by vimuel** [comment]
Hmm. It never said "Ready".  It stayed on "Calculating", even though the project just contained a single file with a single function.

**Comment by nboldi** [comment]
It is possible that another folder had been added but the client lost track of it. Please try the following:

1. Start Atom
2. Reset the Haskell-tools settings: Haskell/Factory Reset
3. Add the folder to Haskell-tools with the one module you would like to refactor.
4. Start the server
5. Try the refactoring

If it does not work, please check if you can do the refactoring using the command line tool.
